### ISSUE TITLE
Is it possible to create report from outside of the repo?

### ISSUE THREAD

**Issue by rzegnam** [bahmutov/cra-ts-code-coverage-example#1]
I wanted to prepare a code coverage report but my tests are not in the same repository as the application code. 
When I generate the report it is empty.
Can I generate the report running Cypress test from a different repository?

**Comment by bahmutov** [comment]
Hmm, you would probably need to rewrite `.nyc_output/out.json` file yourself to update paths to the source files and then run `nyc` to produce report yourself
