### ISSUE TITLE
Missing index.html and buggy react-scripts version

### ISSUE THREAD

**Issue by m3talman** [bahmutov/cra-ts-code-coverage-example#2]
I've downloaded the code and tried running it on my pc but ran into a couple of problems:
1. The "public" folder which should contain "index.html" is missing
2. I had to change "react-scripts" from 3.3.1 to 3.4.0 in package.json because i was getting an error when trying to start the app.
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined

This is a GREAT example project that should definitely be linked to Cypress's documentation regarding code coverage reporting

**Comment by bahmutov** [comment]
This example is linked from https://github.com/cypress-io/code-coverage#external-examples which has quite a few of them, let me check out `public` folder and set up automatic dependency updates and CI here

**Comment by bahmutov** [comment]
I have set up Renovate and updated scripts etc. Should be all good now, let me know if there problems

**Comment by m3talman** [comment]
Latest changes work like a charm.

> This example is linked from https://github.com/cypress-io/code-coverage#external-examples 

Yup, that's where i found it. But if it were up to me, i'd have it put in https://docs.cypress.io/guides/tooling/code-coverage.html#Examples
It would be a bit more visible for amateurs like myself :)
